# permissions for end users to view plays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: play-viewer-role
rules:
- apiGroups:
  - cache.play.js.gl
  resources:
  - plays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.play.js.gl
  resources:
  - plays/status
  verbs:
  - get
