# permissions for end users to edit plays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: play-editor-role
rules:
- apiGroups:
  - cache.play.js.gl
  resources:
  - plays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.play.js.gl
  resources:
  - plays/status
  verbs:
  - get
